"""add_attachment_image_fields

Revision ID: 44fe91537fd5
Revises: c9d608f87623
Create Date: 2026-05-14 11:23:56.134101+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44fe91537fd5"
down_revision: str | None = "c9d608f87623"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attachments", sa.Column("width", sa.Integer(), nullable=True))
    op.add_column("attachments", sa.Column("height", sa.Integer(), nullable=True))
    op.add_column("attachments", sa.Column("alt_text", sa.String(length=512), nullable=True))
    op.add_column("attachments", sa.Column("title", sa.String(length=255), nullable=True))
    op.add_column("attachments", sa.Column("focal_x", sa.Float(), nullable=True))
    op.add_column("attachments", sa.Column("focal_y", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("attachments", "focal_y")
    op.drop_column("attachments", "focal_x")
    op.drop_column("attachments", "title")
    op.drop_column("attachments", "alt_text")
    op.drop_column("attachments", "height")
    op.drop_column("attachments", "width")
    # ### end Alembic commands ###
