"""add_analytics_events

Revision ID: 1f966d693a2d
Revises: 9f3fd65db818
Create Date: 2026-05-14 06:23:04.536210+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f966d693a2d"
down_revision: str | None = "9f3fd65db818"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics_events",
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=True),
        sa.Column("referrer", sa.String(length=1024), nullable=True),
        sa.Column("user_agent_class", sa.String(length=32), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("extra", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analytics_events_event_type"), "analytics_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_analytics_events_occurred_at"), "analytics_events", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_analytics_events_site_id"), "analytics_events", ["site_id"], unique=False
    )
    op.create_index(
        op.f("ix_analytics_events_user_agent_class"),
        "analytics_events",
        ["user_agent_class"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_analytics_events_user_agent_class"), table_name="analytics_events")
    op.drop_index(op.f("ix_analytics_events_site_id"), table_name="analytics_events")
    op.drop_index(op.f("ix_analytics_events_occurred_at"), table_name="analytics_events")
    op.drop_index(op.f("ix_analytics_events_event_type"), table_name="analytics_events")
    op.drop_table("analytics_events")
    # ### end Alembic commands ###
