"""add_page_source_id

Revision ID: 17c7f26e8fde
Revises: 25c6f95918c4
Create Date: 2026-05-14 12:38:05.344721+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17c7f26e8fde"
down_revision: str | None = "25c6f95918c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pages", sa.Column("source_id", sa.String(length=255), nullable=True))
    op.add_column("pages", sa.Column("source_meta", sa.JSON(), nullable=True))
    op.create_index(op.f("ix_pages_source_id"), "pages", ["source_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pages_source_id"), table_name="pages")
    op.drop_column("pages", "source_meta")
    op.drop_column("pages", "source_id")
    # ### end Alembic commands ###
