"""attachment_renditions.claimed_at for worker crash recovery

Revision ID: a523a7f5366b
Revises: b6c01fcf9be2
Create Date: 2026-06-03 20:45:01.816957+00:00

Adds a nullable `claimed_at` DateTime column to `attachment_renditions`
so the rendition worker can detect orphaned `processing` rows (worker
crashed mid-batch, status never advanced to `done` / `failed`) and
reclaim them on the next tick. See #356.

The autogenerated revision pulled in unrelated FTS-shadow-table drops
and a partial-index drop that don't belong to this change; they were
stripped. Only the column add remains.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a523a7f5366b"
down_revision: str | None = "b6c01fcf9be2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "attachment_renditions",
        sa.Column("claimed_at", sa.DateTime(), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("attachment_renditions", "claimed_at")
