"""add_attachment_renditions

Revision ID: 25c6f95918c4
Revises: 44fe91537fd5
Create Date: 2026-05-14 11:54:32.961059+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25c6f95918c4"
down_revision: str | None = "44fe91537fd5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attachment_renditions",
        sa.Column("attachment_id", sa.Integer(), nullable=False),
        sa.Column("size_label", sa.String(length=32), nullable=False),
        sa.Column("storage_key", sa.String(length=128), nullable=False),
        sa.Column("content_type", sa.String(length=127), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("bytes_size", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["attachment_id"], ["attachments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "attachment_id", "size_label", name="uq_attachment_renditions_attachment_size"
        ),
    )
    op.create_index(
        op.f("ix_attachment_renditions_attachment_id"),
        "attachment_renditions",
        ["attachment_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_attachment_renditions_attachment_id"), table_name="attachment_renditions"
    )
    op.drop_table("attachment_renditions")
    # ### end Alembic commands ###
